version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: postgres  # Specify the database name
      POSTGRES_USER: postgres  # Specify the username
      POSTGRES_PASSWORD: risevest  # Specify the password
    ports:
      - "5432:5432"
    
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: my-app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:risevest@postgres:5432/postgres

    command: 
        - npm run test
        - npm run start